name: Ci demo workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  demo-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Print message
        run: echo "github Action working !"
 
      - name: List files in repository
        run: ls -la
